// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formItem': string;
  'formTitle': string;
  'select': string;
}
export const cssExports: CssExports;
export default cssExports;
