// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bioAboutContainer': string;
  'bioBannerImage': string;
  'bioButtons': string;
  'bioContainer': string;
  'bioContent': string;
  'bioIntroContainer': string;
  'bioIntroContainerItem': string;
  'bioIntroContent': string;
  'bioIntroContentFooterText': string;
  'bioSection': string;
  'bioText': string;
  'profilePicContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
