// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconContainer': string;
  'iconText': string;
  'navColor': string;
  'searchColor': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
