// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'extendedNavContainer': string;
  'navContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
