// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'extendedNavContainer': string;
  'linkedInIpsumTitle': string;
  'linkedInLogo': string;
  'navContainer': string;
  'navRight': string;
  'navSection': string;
  'searchBar': string;
  'searchIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
